version: '3.8'
services:
  ## Backend API
  peerserv:
    build: .
    restart: always
    ports:
    - "3002:3002"
    - 9229:9229
    command: node --inspect=0.0.0.0 ./src/index.js
    environment:
      HOSTING_DOMAIN: 'http://localhost:3002'
      PORT: 3002
      SERVER_PRIVATE_KEY: 'f8b4b466417e3fede5f95cb0651fb6371c3c9c0753a3e15c1c30155461d03c18' # Example Key - Use your own key!
      KNEX_DB_CLIENT: mysql
      KNEX_DB_CONNECTION: '{"port":3001,"host":"peerserv-mysql","user":"root","password":"test","database":"peerserv"}'
      NODE_ENV: development
      MIGRATE_KEY: 'my-grate-key'
      DOJO_URL: 'https://staging-dojo.babbage.systems'

  ## Backend database
  peerserv-mysql:
    image: "mysql:8.0"
    platform: linux/x86_64
    hostname: 'peerserv-mysql'
    command: 'mysqld --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync'
    restart: always
    volumes:
     - './data/peerserv-mysql-data:/var/lib/mysql'
    environment:
      MYSQL_HOST: "127.0.0.1"
      MYSQL_TCP_PORT: 3001
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "peerserv"
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10

  ## PHPMyAdmin — Web-based SQL database viewer
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - peerserv-mysql
    environment:
      PMA_HOST: peerserv-mysql
      PMA_PORT: 3001
      PMA_ARBITRARY: 1
    restart: always
    ports:
    - 3003:80
